#!/bin/bash -ex
git clone https://github.com/joemccann/dillinger.git /opt/dillinger
dpkg -i /tmp/node_0.10.25-1_i386.deb
cd /opt/dillinger && npm i -d
mkdir -p /opt/dillinger/public/files

ln -s /etc/nginx/sites-available/dillinger /etc/nginx/sites-enabled/dillinger
chmod +x /etc/init.d/dillinger
adduser --system --no-create-home --group dillinger
mkdir -p /opt/dillinger/run
chown -R dillinger:dillinger /opt/dillinger
update-rc.d dillinger defaults
rm /etc/nginx/sites-enabled/default
